apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: goreact-postgres
          image: ronniewasabi/demo:database
          imagePullPolicy: Always
          ports:
            - containerPort: 5432  
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim