apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: ictlife_infra_interview_may_2020
  POSTGRES_USER: postgres_user
  POSTGRES_PASSWORD: admin123
