apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: goreact-frontend
  name: goreact-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goreact-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goreact-frontend
    spec:
      containers:
      - image: ronniewasabi/demo:frontend
        name: goreact-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
