apiVersion: v1
kind: Service
metadata:
  name: goreact-frontend
  labels:
    app: goreact-frontend
spec:
  type: NodePort
  ports:
  - nodePort: 32728
    port: 3030
    targetPort: 3030
    protocol: TCP
  selector:
   app: goreact-frontend