apiVersion: v1
kind: Service
metadata:
  name: goreact-webapp
  labels:
    app: goreact-webapp
spec:
  type: NodePort
  ports:
  - nodePort: 32727
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
   app: goreact-webapp